export const FETCH_CAR_OF_THE_WEEK = 'FETCH_CAR_OF_THE_WEEK'
export const FETCH_CAR_OF_THE_WEEK_SUCCESS = 'FETCH_CAR_OF_THE_WEEK_SUCCESS'
export const FETCH_CAR_OF_THE_WEEK_FAILURE = 'FETCH_CAR_OF_THE_WEEK_FAILURE'

export const FETCH_CAR_MAKES = 'FETCH_CAR_MAKES'
export const FETCH_CAR_MAKES_SUCCESS = 'FETCH_CAR_MAKES_SUCCESS'
export const FETCH_CAR_MAKES_FAILURE = 'FETCH_CAR_MAKES_FAILURE'


export const FETCH_CAR_MODELS = 'FETCH_CAR_MODELS'
export const FETCH_CAR_MODELS_SUCCESS = 'FETCH_CAR_MODELS_SUCCESS'
export const FETCH_CAR_MODELS_FAILURE = 'FETCH_CAR_MODELS_FAILURE'


export const FETCH_CAR_MAKE_MODEL = 'FETCH_CAR_MAKE_MODEL'
export const FETCH_CAR_MAKE_MODEL_SUCCESS = 'FETCH_CAR_MAKE_MODEL_SUCCESS'
export const FETCH_CAR_MAKE_MODEL_FAILURE = 'FETCH_CAR_MAKE_MODEL_FAILURE'
